excluded:
 - Carthage
 
 disabled_rules:
  - trailing_whitespace
  - unused_closure_parameter
  - cyclomatic_complexity
  - missing_docs

force_cast: warning

line_length: 300

vertical_whitespace:
  max_empty_lines: 3

function_body_length:
  - 300 # warning
  - 400 # error

function_parameter_count:
  - 10 # warning
  - 15 # error

large_tuple:
  - 6 # warning
  - 12 # error
  
type_body_length:
  - 300 # warning
  - 400 # error
  
file_length:
  warning: 1000
  error: 2000
  
type_name:
  min_length: 3 # warning
  max_length:
    warning: 40
    error: 50
  excluded: # excluded via string
    - E

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - vc
    - id
    - in
    - kf
    - x
    - y
    - url
    - id

